Refactor to work in dash

diff --git a/vimv b/vimv
--- a/vimv
+++ b/vimv
@@ -1,44 +1,46 @@
-#!/usr/bin/env bash
+#!/bin/sh
 set -eu
 
-# Lists the current directory's files in Vim, so you can edit it and save to rename them
-# USAGE: vimv [file1 file2]
-# https://github.com/thameera/vimv
+# Bulk rename files with the power of vim
+# USAGE: vimv [file...]
 
-declare -r FILENAMES_FILE=$(mktemp "${TMPDIR:-/tmp}/vimv.XXX")
+FILENAMES_SRC="$(mktemp "${TMPDIR:-/tmp}/vimv.XXX")"
+FILENAMES_DST="$(mktemp "${TMPDIR:-/tmp}/vimv.XXX")"
+cleanup() { rm -f "${FILENAMES_SRC}" "${FILENAMES_DST}"; }
+trap cleanup EXIT
 
-trap '{ rm -f "${FILENAMES_FILE}" ; }' EXIT
+[ "${#}" -gt 0 ] || exit 1
 
-if [ $# -ne 0 ]; then
-    src=( "$@" )
-else
-    IFS=$'\r\n' GLOBIGNORE='*' command eval 'src=($(ls))'
-fi
+printf "%s\n" "$@" | tee "${FILENAMES_SRC}" >"${FILENAMES_DST}"
 
-for ((i=0;i<${#src[@]};++i)); do
-    echo "${src[i]}" >> "${FILENAMES_FILE}"
-done
+ LINES_PRE="$(wc -l "${FILENAMES_DST}")"
+${EDITOR:-vi} "${FILENAMES_DST}"
+LINES_POST="$(wc -l "${FILENAMES_DST}")"
 
-${EDITOR:-vi} "${FILENAMES_FILE}"
-
-IFS=$'\r\n' GLOBIGNORE='*' command eval 'dest=($(cat "${FILENAMES_FILE}"))'
-
-if (( ${#src[@]} != ${#dest[@]} )); then
-    echo "WARN: Number of files changed. Did you delete a line by accident? Aborting.." >&2
+if [ "${LINES_POST}" != "${LINES_PRE}" ]; then
+    printf "%s\n" "WARN: Number of files changed. Did you delete a line by accident? Aborting..." >&2
     exit 1
 fi
 
-declare -i count=0
-for ((i=0;i<${#src[@]};++i)); do
-    if [ "${src[i]}" != "${dest[i]}" ]; then
-        mkdir -p "$(dirname "${dest[i]}")"
-        if git ls-files --error-unmatch "${src[i]}" > /dev/null 2>&1; then
-            git mv "${src[i]}" "${dest[i]}"
-        else
-            mv "${src[i]}" "${dest[i]}"
-        fi
-        ((++count))
-    fi
-done
+# Input: lines of SRC and DEST separated by RS (\x1e)
+move_files() {
+    COUNT="0"
 
-echo "$count" files renamed.
+    while IFS="$(printf '\n\036')" read -r SRC_FILE DST_FILE; do
+        [ "${SRC_FILE}" != "${DST_FILE}" ] || continue
+        [ -e "${SRC_FILE}" ] || {
+            printf "WARN: Skipping nonexistent file: %s\n" "${SRC_FILE}" >&2
+            continue
+        }
+
+        mkdir -p "$(dirname "${DST_FILE}")"
+        mv "${SRC_FILE}" "${DST_FILE}"
+
+        COUNT="$((COUNT + 1))"
+    done
+
+    printf "Renamed %d files.\n" "${COUNT}"
+}
+
+# Join src and dest with the record separator
+paste -d"$(printf '\036')" "${FILENAMES_SRC}" "${FILENAMES_DST}" | move_files
